quarkus:
  http:
    port: 8081

  mongodb:
    #connection-string: mongodb://admin:12345@localhost:27017/willca-product?authSource=admin
    connection-string: mongodb://admin:12345@localhost:27017
    database: willca-product

  rest-client:
    weather-api:
      url: https://api.openweathermap.org
      connect-timeout: 5000
      read-timeout: 10000

weather:
  api-key: ${WEATHER_API_KEY}

product:
  jwt:
    issuer: ${PRODUCT_SECURITY_JWT_ISSUER}
    audience: ${PRODUCT_SECURITY_JWT_AUDIENCE}
    expiration: ${PRODUCT_SECURITY_JWT_EXPIRATION:3600}

mp:
  jwt:
    verify:
      issuer: ${PRODUCT_SECURITY_JWT_ISSUER}
      audiences: ${PRODUCT_SECURITY_JWT_AUDIENCE}
      publickey:
        location: ${PRODUCT_SECURITY_JWT_PUBLIC_KEY_LOCATION}

smallrye:
  jwt:
    sign:
      key:
        location: ${PRODUCT_SECURITY_JWT_PRIVATE_KEY_LOCATION}

    new-token:
      signature-algorithm: RS256
